### ISSUE TITLE
New images

### ISSUE THREAD

**Issue by TomasRoj** [per1234/ino-themes#1]
It would be good to add screenshots from recent versions of ide (1.8.9). If you want I can do that.

**Comment by per1234** [comment]
Why do you think that would be beneficial?

If the only reason is because it says "1.6.11" in the title bar of the IDE in the screenshots, I don't think it's worthwhile.

**Comment by TomasRoj** [comment]
Not at all. New images from modern windows 10 will let users know that this project - isn't death and also it will look better (xp vs 10). Also it is better presentation of the product it self.

**Comment by per1234** [comment]
Regarding "that this project - isn't death", I think you have a good point.

Regarding "it will look better", those screenshots are from Windows 7 not XP, and I very much disagree that the Windows 10 UI looks better. The UI of Windows 10 windows is massively inferior to previous Windows versions. I don't know what they were thinking. But that's beside the point.

I would welcome a pull request for updated screenshots. Please make sure they comply with the following requirements:

- The screenshot must be of the Arduino IDE window only (Alt + PrintScreen).
- The screenshots must be in .png format (because it offers the smallest file size and highest image quality for this type of image).
- The screenshots must be of the **File > Examples > 01.Basics > Blink** sketch
- Scroll the editor window down to the bottom of the sketch (to show the code colors instead of just a huge comment block).
- The cursor must be placed on the on the `void setup()` line (to show how the line highlighter background color interacts with the code colors).
- Select Tools > Board > Arduino/Genuino Uno (because the selection of a 3rd party board might confuse people).
- Compile the sketch before making the screenshot (to show the console and status bar colors).
- Set the Arduino IDE window size to approximately the same size as the screenshots I have, so they're not too big (I believe mine are the default window size used by the Arduino IDE).

Because they're each in a separate branch, you'll need to submit one pull request per theme.

Thanks!

**Comment by TomasRoj** [comment]
Okey I am happy to do that. Is there any size of window parametr?

**Comment by per1234** [comment]
Here's the easiest way to make the IDE use the default window size:

1. (In the Arduino IDE) File > Preferences
2. Click the link at the line following "More preferences can be edited directly in the file". This will open the `Arduino15` folder.
3. Close the Arduino IDE.
4. In the `Arduino15` folder, rename the file preferences.txt to preferences.txt.bak.

When you start the Arduino IDE, it will generate a new preferences.txt with the default preferences settings, including window size. Once you are done with the screenshots, delete the preferences.txt file from the `Arduino15` folder and rename the preferences.txt.bak file back to preferences.txt to restore your custom preferences.

**Comment by TomasRoj** [comment]
Got it, I am working on the screenshots know.
